### ISSUE TITLE
Video not rendering first time on screen sharing

### ISSUE THREAD

**Issue by harshalijain** [AgoraIO-Community/Agora-RN-Quickstart#12]
In the given example, onPressVideo creates a Modal instance in fullscreen mode to display a screen.
However, on first time when we open it, it does not render the video, but renders it second time.
Need help for some possible solution.

**Comment by Matrixbirds** [comment]
@harshalijain 
Please give me your device info + react-native-agora version and execute `react-native info` from your command-line paste it here. I will try to reproduce it ASAP.

**Comment by harshalijain** [comment]
react-native-agora : 2.4.1-alpha.2
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.03 GB / 11.50 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0, 29.0.1
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      babel-preset-react-native: 4.0.1
      react-native-cli: 2.0.1
      react-native: 0.60.0

**Comment by harshalijain** [comment]
The issue is recurring and have tried resolving it by various methods. But it seems consistent.

**Comment by Matrixbirds** [comment]
Pls use the latest version we already fixed the negative num issue
