### ISSUE TITLE
有没有直播相关的demo 旁路拉流怎么弄

### ISSUE THREAD

**Issue by jaapHou** [AgoraIO-Community/Agora-RN-Quickstart#13]

**Comment by Matrixbirds** [comment]
拉流的话这里有个native的[教程](https://docs.agora.io/cn/Interactive%20Broadcast/inject_stream_android?platform=Android) 
rn这边的调用逻辑和native是一样的。
需要用到[addInjectStreamUrl](https://syanbo.github.io/react-native-agora/classes/rtcengine.html#addinjectstreamurl)

**需要注意的是视频格式的支持（文档上有标注），还有需要先开通appId的旁路推流权限。**
