### ISSUE TITLE
Video call or Video brodcasting

### ISSUE THREAD

**Issue by kalyan711987kalyan** [AgoraIO-Community/Agora-RN-Quickstart#14]
I have integrated your sample. It is working great. But, not sure. If it is video call or video brodcasting. Price and limit of views seems difference for both.

I'm looking for live brodcasting.

**Comment by plutoless** [comment]
if you are hosting a live broadcasting + lots of audience, you can use live broadcasting. It can literately support > 10000 audience at one room.

**Comment by kalyan711987kalyan** [comment]
Is "Agora-RN-Quickstart" a broadcasting example?

**Comment by plutoless** [comment]
it's a broadcasting host example. You need to amend the code a little bit to join as an audience. For details you can read agora docs on its website.
