### ISSUE TITLE
Problem building Agora.IO on iOS

### ISSUE THREAD

**Issue by gabrielklose** [AgoraIO-Community/Agora-RN-Quickstart#16]
I get this error message when trying to build: 'AgoraRtcEngineKit / AgoraRtcEngineKit.h' file not found.
![image](https://user-images.githubusercontent.com/26801238/64609236-e31cf800-d3a2-11e9-999a-d6fdd17ab707.png)

I researched various solutions on the internet, and almost all have the following done:
"find AgoraRtcEngineKit.framework from your Pods folder and replace AgoraRtcEngineKit.framework in RCTAgora by dragging it into Your Project -> Libraries -> RCTAgora.xcodeproj -> Build Phases -> Link Binary With Libraries drag_sdk_into_your_project_rctagora_link_binary_with_libraires".

But in my iOS/Pods folder does not have the folder "AgoraRtcEngine_iOS".Can someone help me?

package.json:
{
"name": "agoraguide",
"version": "0.0.1",
"private": true,
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest"
},
"dependencies": {
"react": "16.6.3",
"react-native": "0.58.6",
"react-native-agora": "^2.9.0-alpha.1"
},
"devDependencies": {
"babel-core": "7.0.0-bridge.0",
"babel-jest": "24.9.0",
"jest": "24.9.0",
"metro-react-native-babel-preset": "0.56.0",
"react-test-renderer": "16.6.3"
},
"jest": {
"preset": "react-native"
}
}

Podfile:

target 'agoraguide' do

end

target 'agoraguide-tvOS' do

target 'agoraguide-tvOSTests' do
inherit! :search_paths
end

end

post_install do |installer|
installer.pods_project.targets.each do |target|

targets_to_ignore = %w(React yoga)

if targets_to_ignore.include? target.name
  target.remove_from_project
end
end
end

**Comment by Matrixbirds** [comment]
Pls refer [this](https://github.com/syanbo/react-native-agora/issues/91#issuecomment-527763740), BTW We are recommend to use our latest commit of quick start that you can just use it, don't need manually setup compilation

**Comment by gabrielklose** [comment]
@Matrixbirds Thank you very much!
