### ISSUE TITLE
Problem using Agora IO

### ISSUE THREAD

**Issue by gabrielklose** [AgoraIO-Community/Agora-RN-Quickstart#17]
Hey guys. I was succesful when build your example but right after i tap "join channel" button, i'm getting the error below: 
![image](https://user-images.githubusercontent.com/26801238/65167231-88297780-da18-11e9-81a8-4a7eaf1a0466.png)

Can someone help me?

package.json:
{
  "name": "estudante",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "apisauce": "^1.1.1",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-agora": "^2.9.0-alpha.1",
    "react-native-camera": "^3.4.0",
    "react-native-elements": "^1.2.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-image-crop-picker": "^0.25.2",
    "react-native-image-picker": "^1.1.0",
    "react-native-masked-text": "^1.13.0",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal": "^11.3.1",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.5",
    "react-navigation-drawer": "^2.2.1",
    "react-navigation-stack": "^1.8.0",
    "react-navigation-tabs": "^2.5.3",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "@babel/core": "7.6.0",
    "@babel/runtime": "7.6.0",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.4.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6",
    "redux-devtools": "^3.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
___________________________________________________________

Podfile:
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'estudante' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'estudanteTests' do
    inherit! :search_paths
  end

  use_native_modules!
end

target 'estudante-tvOS' do

  target 'estudante-tvOSTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end

**Comment by gabrielklose** [comment]
it was my mistake, sorry.

**Comment by cristianmgb** [comment]
Hi, @gabrielklose 
How did you solve the error, I have the same error.

Thank you.

**Comment by plutoless** [comment]
@cristianmgb  maybe you can open a new issue and describe your problem in detail

**Comment by cristianmgb** [comment]
> @cristianmgb maybe you can open a new issue and describe your problem in detail

Thanks, I already resolved it.
