### ISSUE TITLE
IOS rn 0.60 build error

### ISSUE THREAD

**Issue by erickbank** [AgoraIO-Community/Agora-RN-Quickstart#18]
I can`t build the app @ rn 0.60 , i ve downloaded the package using npm , and every build i make , returns this error, any solution ?

![65158255-69bb8000-da08-11e9-848f-e4e859d59a57](https://user-images.githubusercontent.com/27246190/65207355-bedaae80-da67-11e9-9121-e7223dabaa07.png)

**Comment by Matrixbirds** [comment]
It looks u r using the [agora-rtc-sdk](https://www.npmjs.com/package/agora-rtc-sdk). This project is using [react-native-agora](https://www.npmjs.com/package/react-native-agora) and react-native  0.59.10.
If you r looking for 0.60.x version's react-native, you can try my own project which using react-native-agora@2.9.0-alpha.1 & react-native 0.60.5

**Comment by erickbank** [comment]
thanks @Matrixbirds  , the real problem was that my project shares code with web react , so i didnt get he was calling the web version.
