### ISSUE TITLE
IOS rn 0.59 build error, 'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by miaojia527** [AgoraIO-Community/Agora-RN-Quickstart#19]
提示两个错误：怎么回事
'React/RCTDefines.h' file not found
'React/RCTBridge.h' file not found

**Comment by Matrixbirds** [comment]
这个报错是因为react的头文件没有在编译阶段找到，可以观察一下编译日志 是从哪里抛出来的 用pod install的方式会生成**.xcworkspace**文件，然后打开这个文件然后运行我们的demo。
如果是cocoapods的方式运行的项目出错，麻烦提供一下编译的完整日志。
