### ISSUE TITLE
ag_rtcfirstremotevideodecode is not supported event type for rctagora

### ISSUE THREAD

**Issue by cristianmgb** [AgoraIO-Community/Agora-RN-Quickstart#21]
![WhatsApp Image 2019-10-08 at 8 22 17 PM](https://user-images.githubusercontent.com/4694439/66444608-77619580-ea09-11e9-95ee-4ddf49630e74.jpeg)

I´m using RN0.60.5 and Agora 2.9.0-alpha.1 - IOS

**Comment by Matrixbirds** [comment]
Since 2.9.0-alpha.1, We deprecate many events(see more details [here](https://github.com/syanbo/react-native-agora/blob/master/CHANGELOG#L9)), you should add listener on `remoteVideoStateChanged` instead of `userMuteVideo`, `userEnableVideo`, `userEnableLocalVideo` & `firstRemoteVideoDecoded`

**Comment by cristianmgb** [comment]
Hello, I follow the example [here](https://github.com/Matrixbirds/agorarnquickstart/blob/master/src/page/agora.js) when I run the app, I get this error and it stops and is on the loading screen when trying to join the video called.

<img width="1025" alt="Captura de Pantalla 2019-10-09 a la(s) 7 55 40 p  m" src="https://user-images.githubusercontent.com/4694439/66530775-d9380300-eace-11e9-8675-3e611bdb1e95.png">

**Comment by plutoless** [comment]
@cristianmgb 
check out the console. it tells you the reason. you have to provide NSCameraUsageDescription key in your project plist in order to have cam access. Same for your mic.

**Comment by cristianmgb** [comment]
Thank you very much, were the access permissions to the camera and microphone.
