### ISSUE TITLE
在安卓上运行报错

### ISSUE THREAD

**Issue by wanwenyun** [AgoraIO-Community/Agora-RN-Quickstart#22]
项目跑起来后，点击join channel后，一直在转圈圈，同时还有警告。麻烦各位解惑。谢谢啦！
![image](https://user-images.githubusercontent.com/49218620/70111366-ed425000-168c-11ea-8efb-490d968d05a9.png)
![image](https://user-images.githubusercontent.com/49218620/70111377-f3383100-168c-11ea-8b34-be831df07f0e.png)

**Comment by plutoless** [comment]
![Uploading image.png…]()

**Comment by wanwenyun** [comment]
@plutoless 
What is the content of the picture? It seems upload failed.

**Comment by plutoless** [comment]
@wanwenyun  101的错误的意思是没有提供合法的appid，请确认下这块有提供
