### ISSUE TITLE
是否支持桌面版？

### ISSUE THREAD

**Issue by 12ndxu** [AgoraIO-Community/Agora-RN-Quickstart#23]
go-flutter 或者 flutter-desktop-embedding

**Comment by Matrixbirds** [comment]
目前react-native微软在做windows版本的维护 考虑到js用户比较多 可以考虑先出windows版的react-native
flutter这块我会去调研一下 也可以提供一些建议给到我们 是希望直播场景用音视频吗？

**Comment by 12ndxu** [comment]
我们是要做线上教育的，可以的话想弄一套代码，四个平台

**Comment by plutoless** [comment]
暂时还不支持，教育方案有兴趣可以参考这个
https://github.com/AgoraIO-Usecase/eEducation
