### ISSUE TITLE
直播只有声音，看不到画面

### ISSUE THREAD

**Issue by bang88** [AgoraIO-Community/Agora-RN-Quickstart#24]
RT

但是同一个流 在web上面是没有问题的。  找了好久了 还不知道哪里的问题。  望告知 

谢谢

**Comment by plutoless** [comment]
有没有调用enableWebSdkInterability接口？和web互通需要调用一下互通接口

**Comment by bang88** [comment]
这个好像默认就是启用的？

Qianze Zhang <notifications@github.com>于2020年1月17日 周五11:15写道：

**Comment by bang88** [comment]
刚手动启用也是一样。

**Comment by plutoless** [comment]
给个频道名 我看下后台

**Comment by bang88** [comment]
@plutoless 可以私聊么

**Comment by bang88** [comment]
@plutoless RN 看不到软件推流的（Web的也看不到），只能听到声音。现在软件推流的话，Web上面是能看到的。

到了RN这边就只有声音了。

**Comment by plutoless** [comment]
上面也说了，麻烦给个频道名和出现问题的时间哈，这样我可以查一下

**Comment by bang88** [comment]
@plutoless channel  `dev.207174dbe2394645aaa03b38f352521d.174`

提工单了，又要来这边，工单那边说客户端接收视频有问题。

现在还是之前的问题，能听到声音，看不到画面
