### ISSUE TITLE
pod faild  

### ISSUE THREAD

**Issue by G1King** [AgoraIO-Community/Agora-RN-Quickstart#27]
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/d/9/AgoraRtcEngine_iOS/2.9.3/AgoraRtcEngine_iOS.podspec.json, error: execution expired 
cd ios 
pod install

**Comment by plutoless** [comment]
我这边能打开，这边检查或者更换下网络吧

**Comment by G1King** [comment]
![image](https://user-images.githubusercontent.com/21077737/74829454-084b6480-534c-11ea-8cf8-11d12f556c66.png)
目前咋又报这个cui错误了呀 AgoraRtcEngine_iOS

**Comment by plutoless** [comment]
做一下pod update吧，感觉是本地cocospod没更新到
