### ISSUE TITLE
Join as a listener

### ISSUE THREAD

**Issue by mtalhagaoglu** [AgoraIO-Community/Agora-RN-Quickstart#31]
Hi. i am start to using this service for my project but i have an issue. i want to join channel as a listener, not broadcaster. i don't want to send my voice or video. is that possible?
i fount that piece of code but i don't know what should be change

`
RtcEngine.joinChannel(this.props.channelName, this.props.uid)
      .then(result => {
        /**
         * ADD the code snippet after join channel success.
         */
      });
`

@Matrixbirds

**Comment by plutoless** [comment]
you can call setClientRole method to set yourself an audience. an audience will not send video/audio but can receive them after joining channel

**Comment by plutoless** [comment]
for reference, you may take a look at our android documentation, RN SDK is basically a one-to-one api mapping of native sdk.

**Comment by LichKing-2234** [comment]
pls try the latest version, and call `setChannelProfile` and `setClientRole`
