### ISSUE TITLE
How Audience became Co-Host

### ISSUE THREAD

**Issue by varunsdcet** [AgoraIO-Community/Agora-RN-Quickstart#35]

**Comment by LichKing-2234** [comment]
`setClientRole` method

**Comment by varunsdcet** [comment]
which parameter pass to this method Host or Co-Host

**Comment by LichKing-2234** [comment]
you can see `RtcEngine.native.d.ts`

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
