### ISSUE TITLE
Don't include code in readme, link files directly.

### ISSUE THREAD

**Issue by ziaulrehman40** [AgoraIO-Community/Agora-RN-Quickstart#36]
I wasted almost 3-4 hours debugging whats going on, opened an issue with `react-native-agora` as well, and had to test on a couple of bare bone new apps. Because Video was not showing any streams on mobile, while my video was being sent to other person.

Issue was that `styles.js` was not updated as per actual `video.js` file in the project(which i copied) and actual `styles.js` file contained different styles.

I think this is a confusion from readme, please mention clearly in readme somewhere that this is an explanation of whats going on and you can use actual files from the project.
Or keep the readme synced.

I might be over-reacting at this time, but this at-least be in your attention.

Thanks.

**Comment by plutoless** [comment]
merged
