### ISSUE TITLE
when click start button,display "NO users connected".is it correct?

### ISSUE THREAD

**Issue by TXLtianxiaolong** [AgoraIO-Community/Agora-RN-Quickstart#39]

**Comment by Matrixbirds** [comment]
It means you don't have peer user in the same channel.

**Comment by xiaoyongchen** [comment]
> It means you don't have peer user in the same channel.

PC terminal can work, should not be this problem

**Comment by LichKing-2234** [comment]
@xiaoyongchen PC terminal can work? could you pls provide more information?
