### ISSUE TITLE
Can not join a channel

### ISSUE THREAD

**Issue by kolyuchii** [AgoraIO-Community/Agora-RN-Quickstart#40]
Hi there!

I'm using this example as it is on iOS emulator.

After starting the application and clicking on the Start Call button, nothing happens. 

The joinChannelSuccess event does not fire. 

The error event returns {"api": "rtc.audio.enabled", "errorCode": 11, "result": ""}

Could someone please clarify what's wrong here?

**Comment by plutoless** [comment]
any logs? btw it's recommended to use an real device instead of iOS emulator

**Comment by meliodev** [comment]
I have faced the same issue for android

**Comment by kolyuchii** [comment]
@meliodev as I found agora SDK doesn't work properly on a simulator

**Comment by meliodev** [comment]
@kolyuchii I am using a physical device. Can you please share your code. I couldn't solve it 😰

**Comment by LichKing-2234** [comment]
pls try the latest version
