### ISSUE TITLE
error: package io.agora.rtc.react does not exist import io.agora.rtc.react.RCTAgoraRtcPackage;

### ISSUE THREAD

**Issue by kongwutw** [AgoraIO-Community/Agora-RN-Quickstart#42]
error: package io.agora.rtc.react does not exist
import io.agora.rtc.react.RCTAgoraRtcPackage;

**Comment by LichKing-2234** [comment]
what version is your RN, and have you link the module?

**Comment by Raja-Aqib-Javed** [comment]
add implementation 'io.agora.rtc:full-sdk:3.1.0'
