### ISSUE TITLE
trying to use face filters in agora react native

### ISSUE THREAD

**Issue by sandys** [AgoraIO-Community/Agora-RN-Quickstart#43]
hi guys,
I'm trying to replicate this example in react native - https://github.com/DeepARSDK/videocall-android-java (this is an agora video call connected to deepar face filters). 

I'm just not able to figure this out - how does one connect the agora video call stream to deepar. 

Can someone help out please ?

**Comment by LichKing-2234** [comment]
@plutoless is this SDK create by us?

**Comment by plutoless** [comment]
sorry it's not created by us. @sandys could you pls create an issue there?

**Comment by qadirali876** [comment]
have you find the solution for this ?
