### ISSUE TITLE
RtcEngine Listeners not triggered

### ISSUE THREAD

**Issue by meliodev** [AgoraIO-Community/Agora-RN-Quickstart#46]
Hi guys,
When a user joins a channel, The RtcEngine listeners (UserJoined, JoinChannelSuccess) are not triggered on android. Do somebody have a solution for this issue ?

**Comment by LichKing-2234** [comment]
it means you are not joining success

**Comment by LichKing-2234** [comment]
you can listener `Warning` and `Error`

**Comment by meliodev** [comment]
@LichKing-2234 Thank you so much for your reply. It helped me to figure out the error. It was ErrorCode '110' which reffers to 'ERR_INVALID_TOKEN'. I just noticed that the App certificate of my project is enabled. Then, I have to use a token.

**Comment by plutoless** [comment]
seems the issue is resolved. feel free to reopen if you still have issues
