### ISSUE TITLE
android crash

### ISSUE THREAD

**Issue by xiaoyongchen** [AgoraIO-Community/Agora-RN-Quickstart#49]
demo crash

**Comment by LichKing-2234** [comment]
any crash log？

**Comment by xiaoyongchen** [comment]
@LichKing-2234 
 const data = await engine.current?.joinChannel(token, channelName, null, 888888);
 console.log('data', data);
data = null;

There are no events listening for the following：
engine.current.addListener('UserJoined', (uid, elapsed) => {
        console.log('UserJoined', uid, elapsed);
        // If new user
        if (peerIds.indexOf(uid) === -1) {
          setPeerIds([...peerIds, uid]);
        }
      });
engine.current.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
        console.log('JoinChannelSuccess', channel, uid, elapsed);
        setJoinSucceed(true);
      });

**Comment by LichKing-2234** [comment]
sorry, I need the crash log.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.

**Comment by xiaoyongchen** [comment]
需要设置正确的渠道和userid






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO-Community/Agora-RN-Quickstart"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午2:08
收件人:&nbsp;"AgoraIO-Community/Agora-RN-Quickstart"<Agora-RN-Quickstart@noreply.github.com&gt;;
抄送:&nbsp;"笑看红尘"<1538627809@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO-Community/Agora-RN-Quickstart] android crash (#49)





 
you can reopen this issue if the problem still exists.
