### ISSUE TITLE
Expo support.

### ISSUE THREAD

**Issue by ramonjobsity** [AgoraIO-Community/Agora-RN-Quickstart#5]
Hi Guys.

I am trying to use expo (v32.0.0). Any help. 

Thanks

**Comment by plutoless** [comment]
hi @ramonjobsity , we did some research over expo topic but eventually decide to not include it in our release as it's introducing too much difference than the original RN one. We may support Expo in the future but for current release there's no Expo support.

**Comment by plutoless** [comment]
close for inactivity for a week

**Comment by shamoons** [comment]
Any update?

**Comment by hiteshpatel1992** [comment]
any Update ??

**Comment by LichKing-2234** [comment]
first, run [`expo eject`](https://docs.expo.io/bare/exploring-bare-workflow/#existing-expo-managed-workflow-apps) to switch to the bare workflow.
second, run [`npx react-native run-ios` `npx react-native run-android`](https://docs.expo.io/bare/hello-world/) to run application.
