### ISSUE TITLE
no any return statement

### ISSUE THREAD

**Issue by jingfreeks** [AgoraIO-Community/Agora-RN-Quickstart#54]
Hello guys,

  rtcengine.current = await RtcEngine.create(appId);

      await rtcengine.current.enableVideo();
      let data = await rtcengine.current.joinChannel(
        null,
        channelName,
        '',
        0,
      );
      console.log('rtcengine', datasss )
      rtcengine.current.addListener('userJoined', (data, elapsed) => {
        console.log('UserJoined', data, elapsed);
        if (peerIds.indexOf(data.uid) === -1) {
          SetPeerIds(oldArray => [...oldArray, data.uid]);
        }
    
      });
      rtcengine.current.addListener('userOffline', (uid, reason) => {
        console.log('UserOffline', uid, reason);
        // let dataPeerId = peerIds;
  
        SetPeerIds(oldArray => oldArray.filter(item => item !== data.uid));
      });
      rtcengine.current.addListener('joinChannelSuccess', (channel, uid, elapsed) => {
        console.log('JoinChannelSuccess', channel, uid, elapsed)
        SetJoinSucceed(true);
      });

no lisener response I cannot see the log of the listener

**Comment by LichKing-2234** [comment]
you can addListener for `warning` and `error`, and check the code

**Comment by jingfreeks** [comment]
got it thanks
