### ISSUE TITLE
how to publish stream url

### ISSUE THREAD

**Issue by jingfreeks** [AgoraIO-Community/Agora-RN-Quickstart#55]
Hello guys I need help on how to publish stream url for live streams for react native

**Comment by LichKing-2234** [comment]
you can use `addInjectStreamUrl`

**Comment by jingfreeks** [comment]
can you give some example for addInjectStreamUrl?

**Comment by LichKing-2234** [comment]
just set the RTMP URL, LiveInjectStreamConfig could be a empty object.
https://agoraio-community.github.io/react-native-agora/classes/rtcengine.html#addinjectstreamurl
