### ISSUE TITLE
TypeError: null is not an object (evaluating 'Agora.FRS30')

### ISSUE THREAD

**Issue by gaurav8809** [AgoraIO-Community/Agora-RN-Quickstart#56]
Link with "react-native link react-native-agora"
![Screenshot_1599129522](https://user-images.githubusercontent.com/59197887/92104968-bf4a9180-edff-11ea-9dc5-c5a1fd21ec4b.png)

**Comment by gaurav8809** [comment]
@LichKing-2234 Agora is not defined

**Comment by LichKing-2234** [comment]
which version of SDK did you use?

**Comment by gaurav8809** [comment]
> which version of SDK did you use?

Version: ^3.0.1-rc.4

**Comment by LichKing-2234** [comment]
your code is for 1.x version, you can refer to the code of master.

**Comment by gaurav8809** [comment]
Version: 3.0.1-rc.4
![Screenshot_1599142034](https://user-images.githubusercontent.com/59197887/92125754-fe3b1000-ee1c-11ea-8eb1-a1475d15eb36.png)

Tried with new sample code 
But getting this error

**Comment by LichKing-2234** [comment]
please double-check.
```
git clone https://github.com/AgoraIO-Community/Agora-RN-Quickstart.git
cd Agora-RN-Quickstart
npm i
npx pod-install
react-native run-android
```

**Comment by gaurav8809** [comment]
> please double-check.
> 
> ```
> git clone https://github.com/AgoraIO-Community/Agora-RN-Quickstart.git
> cd Agora-RN-Quickstart
> npm i
> npx pod-install
> react-native run-android
> ```

Sample project working but when I try it in Javascript 
It display above error

**Comment by LichKing-2234** [comment]
could you share your javascript code?

**Comment by gaurav8809** [comment]
import React, { Component } from 'react';
import { View, StyleSheet, Text, Dimensions, TouchableOpacity} from 'react-native';

import RtcEngine, {RtcLocalView, RtcRemoteView, VideoRenderMode} from 'react-native-agora'

class Video extends Component {
    _engine: RtcEngine;
    constructor(props) {
        super(props);
        this.state = {
            peerIds: [], //Array for storing connected peers
            uid: Math.floor(Math.random() * 100), //Generate a UID for local user
            appID: this.props.appID, //Enter the App ID generated from the Agora Website
            channelName: this.props.channelname, //Channel Name for the current session
            vidMute: false, //State variable for Video Mute
            audMute: false, //State variable for Audio Mute
            joinSucceed: false, //State variable for storing success
        };
    };

    async componentDidMount() {
        this.init();
    };

    init = async () => {
        const {appID} = this.state
        this._engine = await RtcEngine.create(appID)
        await this._engine.enableVideo()

        this._engine.addListener('UserJoined', (uid, elapsed) => {
            console.log('UserJoined', uid, elapsed)
            // Get current peer IDs
            const {peerIds} = this.state
            // If new user
            if (peerIds.indexOf(uid) === -1) {
                this.setState({
                    // Add peer ID to state array
                    peerIds: [...peerIds, uid]
                })
            }
        })

        this._engine.addListener('UserOffline', (uid, reason) => {
            console.log('UserOffline', uid, reason)
            const {peerIds} = this.state
            this.setState({
                // Remove peer ID from state array
                peerIds: peerIds.filter(id => id !== uid)
            })
        })

        // If Local user joins RTC channel
        this._engine.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
            console.log('JoinChannelSuccess', channel, uid, elapsed)
            // Set state variable to true
            this.setState({
                joinSucceed: true
            })
        })
    }

    startCall = async () => {
        // Join Channel using null token and channel name
        await this._engine?.joinChannel(null, this.state.channelName, null, 0)
    };

    async endCall() {
        // RtcEngine.destroy();
        this.props.setCall(false);

        await this._engine?.leaveChannel()
        this.setState({peerIds: [], joinSucceed: false})
    };

    _renderVideos = () => {
        const {joinSucceed} = this.state
        return joinSucceed ? (
            <View style={styles.fullView}>
                <RtcLocalView.SurfaceView
                    style={styles.max}
                    channelId={this.state.channelName}
                    renderMode={VideoRenderMode.Hidden}/>
                {this._renderRemoteVideos()}
            </View>
        ) : null
    }

    _renderRemoteVideos = () => {
        const {peerIds} = this.state
        return (
            <ScrollView
                style={styles.remoteContainer}
                contentContainerStyle={{paddingHorizontal: 2.5}}
                horizontal={true}>
                {peerIds.map((value, index, array) => {
                    return (
                        <RtcRemoteView.SurfaceView
                            style={styles.remote}
                            uid={value}
                            channelId={this.state.channelName}
                            renderMode={VideoRenderMode.Hidden}
                            zOrderMediaOverlay={true}/>
                    )
                })}
            </ScrollView>
        )
    };

    render() {
        return (
            <View style={styles.max}>
                <View style={styles.max}>
                    <View style={styles.buttonHolder}>
                        <TouchableOpacity
                            onPress={this.startCall}
                            style={styles.button}>
                            <Text style={styles.buttonText}> Start Call </Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                            onPress={this.endCall}
                            style={styles.button}>
                            <Text style={styles.buttonText}> End Call </Text>
                        </TouchableOpacity>
                    </View>
                    {this._renderVideos()}
                </View>
            </View>
        );
        // return this.videoView();
    }
}

export default Video;

const dimensions = {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
};

const styles = StyleSheet.create({
    buttonBar: {
        height: 50,
        backgroundColor: '#0093E9',
        display: 'flex',
        width: '100%',
        position: 'absolute',
        bottom: 0,
        left: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignContent: 'center',
    },
    localVideoStyle: {
        width: 140,
        height: 160,
        position: 'absolute',
        top: 5,
        right: 5,
        zIndex: 100,
    },
    iconStyle: {
        fontSize: 34,
        paddingTop: 15,
        paddingLeft: 40,
        paddingRight: 40,
        paddingBottom: 15,
        borderRadius: 0,
    },
    max: {
        flex: 1,
    },
    buttonHolder: {
        height: 100,
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    button: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#0093E9',
        borderRadius: 25,
    },
    buttonText: {
        color: '#fff',
    },
    fullView: {
        width: dimensions.width,
        height: dimensions.height - 100,
    },
    remoteContainer: {
        width: '100%',
        height: 150,
        position: 'absolute',
        top: 5
    },
    remote: {
        width: 150,
        height: 150,
        marginHorizontal: 2.5
    },
    noUserText: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        color: '#0093E9',
    },
});

**Comment by LichKing-2234** [comment]
the code seem like right. could you make a demo to recurrence your problem and let me to test it.

**Comment by gaurav8809** [comment]
I think it's working now but there is no such options related to call like End call, Toggle Audio-Video

**Comment by LichKing-2234** [comment]
call `enableVideo` to enable video mode, call `disableVideo` to switch to audio mode.

**Comment by gaurav8809** [comment]
Where I can see this latest sdk version doc?

**Comment by LichKing-2234** [comment]
you can refer to the Andorid or iOS doc.
https://docs.agora.io/en/Interactive%20Broadcast/product_live?platform=All%20Platforms

[RN API doc](https://agoraio-community.github.io/react-native-agora/globals.html)

**Comment by gaurav8809** [comment]
But I can not find function code (How to use functions) in this doc
https://agoraio-community.github.io/react-native-agora/globals.html

**Comment by LichKing-2234** [comment]
@gaurav8809 how to use functions you can refer to android or ios doc.

**Comment by gaurav8809** [comment]
Hey @LichKing-2234 Now SDK is working.
Get expected behaviour 
Thanks.
