### ISSUE TITLE
Clicking the Start Call doesn't do anything

### ISSUE THREAD

**Issue by timi-codes** [AgoraIO-Community/Agora-RN-Quickstart#57]
`startCall` method is called but nothing happens when I click the start call button

**Comment by timi-codes** [comment]
Using legacy version also give this error TypeError: undefined is not an object (evaluating '_reactNativeAgora.default.on')

**Comment by LichKing-2234** [comment]
> `startCall` method is called but nothing happens when I click the start call button

@timi-codes pls provide our SDK log, you can refer to [setLogFile](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08)
