### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by jingfreeks** [AgoraIO-Community/Agora-RN-Quickstart#58]
Hi guys How to fixed the black screen when join first time

**Comment by LichKing-2234** [comment]
could you provide the SDK log? you can get more info from `setLogFile` method.

**Comment by LichKing-2234** [comment]
by the way, you can listen to the `Warning` and `Error` event to get more info.

**Comment by LichKing-2234** [comment]
you can reopen this issue if this problem still exists.
