### ISSUE TITLE
Clicking on Start Call returns an error

### ISSUE THREAD

**Issue by ShadyStego** [AgoraIO-Community/Agora-RN-Quickstart#62]
Hi, 

I followed the instructions and was able to see two buttons: `Start Call` and `End Call`. However, when I clicked on `Start Call`, it doesn't do anything and the console logged `Error 110`. Clicking on `End Call` also doesn't do anything and the cosole logged `Error 18`. 

![image](https://user-images.githubusercontent.com/6054688/93010180-5c16d880-f53e-11ea-9c5a-a31f241aaaee.png)

**Comment by LichKing-2234** [comment]
your appId enables certificate, you should call `joinChannel` with the token.
https://docs.agora.io/en/faq/token_error

**Comment by ShadyStego** [comment]
Thanks @LichKing-2234 . I created another app that doesn't require certificates. Now when I click on start call, I'm getting this: 
<img width="357" alt="Screen Shot 2020-09-13 at 9 37 22 AM" src="https://user-images.githubusercontent.com/6054688/93023580-d5e1ad00-f5a4-11ea-976a-11a5d210ffc9.png">

**Comment by ShadyStego** [comment]
Next, I tried to use an actual device and run it via XCode. The camera/ video seems to be working now.

**Comment by LichKing-2234** [comment]
@ShadyStego Yes, the iOS simulator doesn't support the camera.
