### ISSUE TITLE
how to unsubscribe all listeners in useEffect?

### ISSUE THREAD

**Issue by eleviven** [AgoraIO-Community/Agora-RN-Quickstart#65]
I'm using function component. How can i unsubscribe all listeners and leave?

**Comment by LichKing-2234** [comment]
https://stackoverflow.com/questions/55139386/componentwillunmount-with-react-useeffect-hook

**Comment by eleviven** [comment]
> https://stackoverflow.com/questions/55139386/componentwillunmount-with-react-useeffect-hook

My question was about the remove listener of the agora. I think I found it, the _engine.removeAllListeners () method.

I solved it this way

```js
  navigation.addListener('focus', async () => {
    await init();
    await startCall();
  });

  navigation.addListener('blur', async () => {
    await endCall(false);
    await removeListeners();
  });
```
