### ISSUE TITLE
Playing Error

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Community/Agora-RN-Quickstart#66]
I'd like to run this sample app, but I always got the below error.
Could you help me to get any idea to fix it?

![KakaoTalk_Photo_2021-03-10-01-59-51](https://user-images.githubusercontent.com/8732515/110508427-56442d80-8144-11eb-8faa-6a08bd50db80.jpeg)

**Comment by LichKing-2234** [comment]
pls check your npm server is running.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
