### ISSUE TITLE
Supported background?

### ISSUE THREAD

**Issue by ksielyov** [AgoraIO-Community/Agora-RN-Quickstart#67]
Hello! Can I checking calls from background? For example as in Telegram, when the app is not active device can show calls from another user.

**Comment by plutoless** [comment]
you will need push notifications, together with callkit & connection service to make this work.

**Comment by ksielyov** [comment]
Thx. I am using Firebase, I will try it.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
