### ISSUE TITLE
How to stop entire channel broadcasting

### ISSUE THREAD

**Issue by Joshig99** [AgoraIO-Community/Agora-RN-Quickstart#69]
Hi first i started broadcasting, then some people are added to my channel as co-hosts. i want to stop my broadcasting and also my co-hosts broadcasting. this means there is no broadcasting between me and  co-hosts and also between co-hosts when i stop my broadcasting.

**Comment by plutoless** [comment]
just leave the channel.

**Comment by RoJoHub** [comment]
![image](https://user-images.githubusercontent.com/15648309/114368666-345d2100-9bb0-11eb-9e30-1a79da73521d.png)
Please use `mute` api.

**Comment by Joshig99** [comment]
Hi @RoJoHub @plutoless, thanks for your reply.
leaveChannel and mute api is just stoping my broadcasting between me and co-host and audience. but i want to stop  co-hosts broadcasting between co-hosts and audience also.  When i wish to leaving from my channel i want to remove co-hosts also from my channel
