### ISSUE TITLE
运行实例项目报错

### ISSUE THREAD

**Issue by xuya227939** [AgoraIO-Community/Agora-RN-Quickstart#73]
![25741627271731_ pic_hd](https://user-images.githubusercontent.com/16217324/126930995-d5547161-9fe5-4aad-bcc5-47d9e081dae1.jpg)

请问这个报错如何解决

**Comment by LichKing-2234** [comment]
这个仓库已经不维护了，请参考sdk仓库中的example，有问题再反馈

**Comment by xuya227939** [comment]
好的

Arthas ***@***.***> 于2021年7月26日周一 下午1:01写道：
