### ISSUE TITLE
Using Picture to show Remote  Users in Audio Call.

### ISSUE THREAD

**Issue by muhamadjawad** [AgoraIO-Community/Agora-RN-Quickstart#77]
Hi i want to implement Audio call in Agora. I have implemented every thing the audio, mic, speaker every thing is working fine. But i want to show my image to the remote users. The demo only contains code for video call and that is using `RtcLocalView.SurfaceView` for local View.
Can anyone please help me what to use .I m stuck here

**Comment by LichKing-2234** [comment]
seems related to https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/76
