### ISSUE TITLE
xcode build失败

### ISSUE THREAD

**Issue by pokerface0206** [AgoraIO-Community/Agora-RN-Quickstart#8]
我在xcode build的时候，直接失败 ，报错'React/RCTBridgeModule.h' file not found。请问一下这个怎么解决呢？

**Comment by Matrixbirds** [comment]
@pokerface0206 
看上去是缺少Target Dependencies.
找到主项目的 Target -> Build Phases -> Target Dependencies 
![image](https://user-images.githubusercontent.com/9990676/58303904-b5786700-7e24-11e9-8b52-4dc63f195f38.png)

**Comment by soulmatecm** [comment]
我也是这个报着个错，按上述加上之后，依然报错

**Comment by Matrixbirds** [comment]
@soulmatecm 麻烦提供一下你的报错日志

**Comment by wuichen** [comment]
@soulmatecm @pokerface0206 
i think this thread provides the solutions for this error. https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found
